[2024-04-13T15:06:00.451+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: challenge_dag.load_task manual__2024-04-13T15:05:51.926021+00:00 [queued]>
[2024-04-13T15:06:00.456+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: challenge_dag.load_task manual__2024-04-13T15:05:51.926021+00:00 [queued]>
[2024-04-13T15:06:00.456+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-04-13T15:06:00.456+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-04-13T15:06:00.456+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-04-13T15:06:00.487+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): load_task> on 2024-04-13 15:05:51.926021+00:00
[2024-04-13T15:06:00.491+0000] {standard_task_runner.py:55} INFO - Started process 28592 to run task
[2024-04-13T15:06:00.494+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'challenge_dag', 'load_task', 'manual__2024-04-13T15:05:51.926021+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/challenge_dag.py', '--cfg-path', '/tmp/tmph2g21pcw']
[2024-04-13T15:06:00.495+0000] {standard_task_runner.py:83} INFO - Job 42: Subtask load_task
[2024-04-13T15:06:00.550+0000] {task_command.py:388} INFO - Running <TaskInstance: challenge_dag.load_task manual__2024-04-13T15:05:51.926021+00:00 [running]> on host codespaces-3318c7
[2024-04-13T15:06:00.713+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=challenge_dag
AIRFLOW_CTX_TASK_ID=load_task
AIRFLOW_CTX_EXECUTION_DATE=2024-04-13T15:05:51.926021+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-04-13T15:05:51.926021+00:00
[2024-04-13T15:06:00.714+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-04-13T15:06:00.715+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo -e ".separator ","\n.import --skip 1 /workspaces/hands-on-introduction-data-engineering-4395021/lab/challenge/challenge-transform-data.csv top_level_domains" | sqlite3 /workspaces/hands-on-introduction-data-engineering-4395021/lab/challenge/challenge-load-db.db']
[2024-04-13T15:06:00.723+0000] {subprocess.py:86} INFO - Output:
[2024-04-13T15:06:00.727+0000] {subprocess.py:93} INFO - /workspaces/hands-on-introduction-data-engineering-4395021/lab/challenge/challenge-transform-data.csv:2: expected 8 columns but found 3 - filling the rest with NULL
[2024-04-13T15:06:00.727+0000] {subprocess.py:93} INFO - /workspaces/hands-on-introduction-data-engineering-4395021/lab/challenge/challenge-transform-data.csv:3: expected 8 columns but found 3 - filling the rest with NULL
[2024-04-13T15:06:00.727+0000] {subprocess.py:93} INFO - /workspaces/hands-on-introduction-data-engineering-4395021/lab/challenge/challenge-transform-data.csv:4: expected 8 columns but found 3 - filling the rest with NULL
[2024-04-13T15:06:00.727+0000] {subprocess.py:93} INFO - /workspaces/hands-on-introduction-data-engineering-4395021/lab/challenge/challenge-transform-data.csv:5: expected 8 columns but found 3 - filling the rest with NULL
[2024-04-13T15:06:00.727+0000] {subprocess.py:93} INFO - /workspaces/hands-on-introduction-data-engineering-4395021/lab/challenge/challenge-transform-data.csv:6: expected 8 columns but found 3 - filling the rest with NULL
[2024-04-13T15:06:00.728+0000] {subprocess.py:93} INFO - /workspaces/hands-on-introduction-data-engineering-4395021/lab/challenge/challenge-transform-data.csv:7: expected 8 columns but found 3 - filling the rest with NULL
[2024-04-13T15:06:00.728+0000] {subprocess.py:93} INFO - /workspaces/hands-on-introduction-data-engineering-4395021/lab/challenge/challenge-transform-data.csv:8: expected 8 columns but found 3 - filling the rest with NULL
[2024-04-13T15:06:00.728+0000] {subprocess.py:93} INFO - /workspaces/hands-on-introduction-data-engineering-4395021/lab/challenge/challenge-transform-data.csv:9: expected 8 columns but found 3 - filling the rest with NULL
[2024-04-13T15:06:00.728+0000] {subprocess.py:93} INFO - /workspaces/hands-on-introduction-data-engineering-4395021/lab/challenge/challenge-transform-data.csv:10: expected 8 columns but found 3 - filling the rest with NULL
[2024-04-13T15:06:00.728+0000] {subprocess.py:93} INFO - /workspaces/hands-on-introduction-data-engineering-4395021/lab/challenge/challenge-transform-data.csv:11: expected 8 columns but found 3 - filling the rest with NULL
[2024-04-13T15:06:00.728+0000] {subprocess.py:93} INFO - /workspaces/hands-on-introduction-data-engineering-4395021/lab/challenge/challenge-transform-data.csv:12: expected 8 columns but found 3 - filling the rest with NULL
[2024-04-13T15:06:00.751+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-04-13T15:06:00.783+0000] {taskinstance.py:1318} INFO - Marking task as SUCCESS. dag_id=challenge_dag, task_id=load_task, execution_date=20240413T150551, start_date=20240413T150600, end_date=20240413T150600
[2024-04-13T15:06:00.827+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2024-04-13T15:06:00.840+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
