[2024-04-12T12:43:41.677+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: transform_dag.transform_task manual__2024-04-12T12:43:38.258420+00:00 [queued]>
[2024-04-12T12:43:41.683+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: transform_dag.transform_task manual__2024-04-12T12:43:38.258420+00:00 [queued]>
[2024-04-12T12:43:41.683+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-04-12T12:43:41.683+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-04-12T12:43:41.683+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-04-12T12:43:41.715+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): transform_task> on 2024-04-12 12:43:38.258420+00:00
[2024-04-12T12:43:41.718+0000] {standard_task_runner.py:55} INFO - Started process 36179 to run task
[2024-04-12T12:43:41.721+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'transform_dag', 'transform_task', 'manual__2024-04-12T12:43:38.258420+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/transform_dag.py', '--cfg-path', '/tmp/tmphngxz616']
[2024-04-12T12:43:41.722+0000] {standard_task_runner.py:83} INFO - Job 12: Subtask transform_task
[2024-04-12T12:43:41.774+0000] {task_command.py:388} INFO - Running <TaskInstance: transform_dag.transform_task manual__2024-04-12T12:43:38.258420+00:00 [running]> on host codespaces-3318c7
[2024-04-12T12:43:41.955+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=transform_dag
AIRFLOW_CTX_TASK_ID=transform_task
AIRFLOW_CTX_EXECUTION_DATE=2024-04-12T12:43:38.258420+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-04-12T12:43:38.258420+00:00
[2024-04-12T12:43:41.964+0000] {logging_mixin.py:137} WARNING - /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/transform_dag.py:18 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2024-04-12T12:43:41.967+0000] {python.py:177} INFO - Done. Returned value was: None
[2024-04-12T12:43:41.971+0000] {taskinstance.py:1318} INFO - Marking task as SUCCESS. dag_id=transform_dag, task_id=transform_task, execution_date=20240412T124338, start_date=20240412T124341, end_date=20240412T124341
[2024-04-12T12:43:42.013+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2024-04-12T12:43:42.023+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
